name: Test
on:
  workflow_dispatch
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: generate file
        run: touch test.txt
      - name: get file path
        id: testFile
        run: |
            path=$(find (cd ..; pwd) . -name test.txt -type f)
            echo $path
            echo "path=$path" >> $GITHUB_OUTPUT
      - name: Print path
        run: echo ${{ steps.testFile.outputs.path }}
