name: Test
on:
  workflow_dispatch
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: generate file
        run: touch test.txt
      - name: get file path
        id: testFile
        run: |
            path=$(find . -name test.txt -type f | head -1)
            echo $path.path
            echo "path=$path.path" >> $GITHUB_OUTPUT
      - name: Print path
        run: echo ${{ steps.testFile.outputs.path }}
