name: Test

on:
  workflow_dispatch:
    inputs:
      aws_upload:
        description: 'Upload build to Bell/AWS S3 Bucket'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: 'Build stuff'
    runs-on: ubuntu-latest
    
    steps:    
      - name: Set upload dir env
        run: echo "UPLOAD_DIR=$(echo $HOME)/upload" >> $GITHUB_ENV
      
      - name: create dir
        run: mkdir $UPLOAD_DIR
      
      - name: create file
        run: touch $UPLOAD_DIR/names
      
      - name: list dir
        run: ls -la $UPLOAD_DIR

      - name: reuse workflow
        uses: rodrigo-queiroz-deltatre/test2/.github/workflows/blank.yml@main
        with:
          username: 'Rodrigo'
